# Player
# =============
MBTN_RIGHT cycle pause
MBTN_LEFT_DBL cycle fullscreen
p cycle pause
ESC set fullscreen no
F11 cycle fullscreen
Ctrl+a cycle ontop
Ctrl+b cycle border
h cycle deband
Ctrl+h cycle-values hwdec "dxva2-copy" "no"
CTRL+l script-message switch-vf
CTRL+p script-message switch-shaders
DEL	  script-binding osc-cycle-never-auto
F     script-binding quality_menu/video_formats_toggle
Alt+f script-binding quality_menu/audio_formats_toggle

# Volume & Audio
# =============
AXIS_UP add volume 5
AXIS_DOWN add volume -5
UP add volume 5
DOWN add volume -5
m cycle mute
a cycle audio
Ctrl+UP add speed +0.1
Ctrl+DOWN add speed -0.1
F3 add audio-delay -0.01
F4 add audio-delay +0.01

# Seeking
# =============
RIGHT seek 5
LEFT seek -5
Shift+RIGHT seek 1
Shift+LEFT seek -1
Ctrl+RIGHT frame-step
Ctrl+LEFT frame-back-step
j seek -10
l seek 10
, frame-back-step
. frame-step
H no-osd sub-seek -1
L no-osd sub-seek 1
PGDWN add chapter -1
PGUP add chapter +1

# Playlists
# =============
] playlist-next
[ playlist-prev

# Subtitles
# =============
s cycle sub
F1 add sub-delay -0.01
F2 add sub-delay +0.01
u cycle-values sub-ass-override "yes" "force"; cycle-values sub-use-margins "no" "yes"

# Screenshots
# =============
F5 screenshot video
F6 screenshot
F7 screenshot window

# clipshot.lua
Shift+F5 script-binding clipshot-video
Shift+F6 script-binding clipshot-subs
Shift+F7 script-binding clipshot-window

# progressbar.lua
# . script-binding progressbar/step-forward
# , script-binding progressbar/step-backward
# c script-binding progressbar/toggle-inactive-bar
# tab script-binding progressbar/request-display
# mouse_btn0 script-binding progressbar/left-click

# mfpbar.lua
Space cycle pause; script-binding mfpbar/maximize