# example config for mfpbar.
#
# NOTE: all colors values are in css-style hex color:
# https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color

# height of the progressbar when hovering over it
# the value is in percentage, 2 means 2% of the screen height
pbar_height=2
# height of the progressbar when minimized.
# set to 0 disable minimized state.
pbar_minimized_height=0
# color of progressbar
pbar_color=2775E3
# color of the progressbar background
pbar_bg_color=333333
# hide progressbar when fullscreen
pbar_fullscreen_hide=yes


# height of the cachebar in percentage. set to 0 to disable.
cachebar_height=0.25
cachebar_color=1C6C89
# color of the uncached area.
cachebar_uncached_color=CC3A2A8F

# what to show in the right hand side of the timeline. valid options are:
# 	time-remaining: shows the remaining time (default)
# 	playtime-remaining: shows the remaining time scaled by the playback speed
timeline_rhs=time-remaining

# color of the hover bar
hover_bar_color=BDAE93

# color of the font/text
font_color=EBEBEB
# font size
font_size=32
# horizontal font padding
font_pad=4
# font borders
font_border_width=3
font_border_color=333333

# trigger range for the progressbar
# uses pixel count by default, e.g "40" means 40 pixels
# append '%' to use percentage of window height e.g "40%"
proximity=48

# width of preview border. set to 0 to disable.
preview_border_width=3
preview_border_color=333333

# maximum thumbnail size (when using the osc's preview api)
max_thumb_size=360

# chapter marker size. set 0 to disable.
chapter_marker_size=6
chapter_marker_color=BDAE93
# chapter marker border width. set 0 to disable.
chapter_marker_border_width=2
chapter_marker_border_color=333333
# proximity for triggering chapter snapping. 0 to disable chapter snapping.
# can use either pixel or percentage as `proximity`
chapter_proximity=0.67%

# seconds before auto minimizing. set to 0 to disable auto-minimize.
minimize_timeout=3
# default timeout duration (in seconds) for the "maximize" binding.
maximize_timeout=1.5
# automatically maximize the progressbar when seeking.
maximize_on_seek=yes

# when hovering over a chapter diamond, if the time position used for displaying
# the preview should be locked to the middle of the diamond / chapter time.
hover_lock_to_chapter_time=yes
