output_directory=C:\Users\Roak\Videos\mpv_webm
# Sets the output format, from a few predefined ones.
# Currently we have:
# av1
# hevc
# webm-vp9 (libvpx-vp9/libopus)
# webp
# avc (h264/AAC)
# avc-nvenc (h264-NVENC/AAC)
# webm-vp8 (libvpx/libvorbis)
# gif
# mp3 (libmp3lame)
# and raw (rawvideo/pcm_s16le).
output_format=hevc
# avc for sakugabooru
twopass=no
apply_current_filters=yes
scale_height=-1 
# 480 for sakugabooru
target_filesize=0
crf=16
fps=-1
force_square_pixels=yes
additional_flags=--vf-add=format=yuv420p --ovcopts-add=profile=high --ovcopts-add=level=4 --ovcopts=aq-mode=3 
# Note — append --vf-add=fps="24000/1001" (or whatever your source framerate is) for sakugabooru cutting, as long as the FPS stat is broken in mpv's ovc encoder